name: 'databricks_transformation'
version: '1.0.0'
config-version: 2

profile: 'databricks_transformation'  # This should match the profile name in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  databricks_transformation:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +file_format: iceberg  # Specify Iceberg format for marts layer
      +location_root: "s3://test-kr9948/sample_dbt/iceberg-output/" # Update with your S3 bucket path