version: 2

models:
  - name: stg_userdata
    description: "Staged user data from S3 parquet files"
    columns:
      - name: id
        description: "Unique identifier for the user"
        tests:
          - unique
          - not_null

  - name: int_userdata_enriched
    description: "Enriched user data with additional calculated fields"
    columns:
      - name: id
        description: "Unique identifier for the user"
        tests:
          - unique
          - not_null
      - name: age
        description: "Calculated age based on birthdate"
      - name: salary_bracket
        description: "Salary category (Low, Medium, High)"
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High', 'Unknown']

  - name: country_aggregation
    description: "Country-wise aggregation of user data"
    columns:
      - name: country
        description: "Country name"
        tests:
          - unique
          - not_null
      - name: total_users
        description: "Total number of users in the country"
      - name: avg_salary
        description: "Average salary in the country"
      - name: median_salary
        description: "Median salary in the country"
      - name: total_salary
        description: "Sum of all salaries in the country"